### ISSUE TITLE
Maybe a problem with img allocation

### ISSUE THREAD

**Issue by Kum1ta** [seekrs/MacroLibX#58]
We noticed that the use of RAM only increases until the PC freezes. It gets faster and faster if you put pixels in the image. We noticed this in the function below called in a loop with mlx_loop_hook()

```c
void	function(t_mlx *mlx)
{
	if (mlx->img)
		mlx_destroy_image(mlx->mlx, mlx->img);
	mlx->img = mlx_new_image(mlx->mlx, WIDTH, HEIGHT);
	mlx_put_image_to_window(mlx->mlx, mlx->win, mlx->img, 0, 0);
}
```

**Comment by Kbz-8** [comment]
fixed in 2,0
